version: '3'

services:
  app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

  nginx:
      build:
        context: .
        dockerfile: Dockerfile.nginx
      ports:
        - 8080:80
      depends_on:
        - app
      volumes:
        - my-volume-nginx:/usr/share/nginx/html

  db:
    image: mysql:8.0.30-debian
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 1GB

volumes:
  my-volume-nginx:
    external: true
